apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabpk-controller-manager
  namespace: cabpk-system
spec:
  template:
    spec:
      containers:
      - image: ${CABPK_MANAGER_IMAGE}
        name: manager
