apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- provider-components-kubeadm.yaml
- provider-components-cluster-api.yaml
- provider-components-vsphere.yaml
patchesStrategicMerge:
- cabpk_image_patch.yaml
- manager_tolerations_patch.yaml
