apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  username: ${VSPHERE_B64ENCODED_USERNAME}
  password: ${VSPHERE_B64ENCODED_PASSWORD}
