apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: vspheremachineproviderconfigs.vsphereproviderconfig.sigs.k8s.io
spec:
  group: vsphereproviderconfig.sigs.k8s.io
  names:
    kind: VsphereMachineProviderConfig
    plural: vspheremachineproviderconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        kubeadmConfiguration:
          properties:
            init:
              properties:
                apiVersion:
                  type: string
                bootstrapTokens:
                  items:
                    properties:
                      description:
                        type: string
                      expires:
                        format: date-time
                        type: string
                      groups:
                        items:
                          type: string
                        type: array
                      token:
                        type: object
                      ttl:
                        type: object
                      usages:
                        items:
                          type: string
                        type: array
                    required:
                    - token
                    type: object
                  type: array
                kind:
                  type: string
                localAPIEndpoint:
                  properties:
                    advertiseAddress:
                      type: string
                    bindPort:
                      format: int32
                      type: integer
                  required:
                  - advertiseAddress
                  - bindPort
                  type: object
                nodeRegistration:
                  properties:
                    criSocket:
                      type: string
                    kubeletExtraArgs:
                      type: object
                    name:
                      type: string
                    taints:
                      items:
                        type: object
                      type: array
                  type: object
              type: object
            join:
              properties:
                apiVersion:
                  type: string
                caCertPath:
                  type: string
                controlPlane:
                  properties:
                    localAPIEndpoint:
                      properties:
                        advertiseAddress:
                          type: string
                        bindPort:
                          format: int32
                          type: integer
                      required:
                      - advertiseAddress
                      - bindPort
                      type: object
                  type: object
                discovery:
                  properties:
                    bootstrapToken:
                      properties:
                        apiServerEndpoint:
                          type: string
                        caCertHashes:
                          items:
                            type: string
                          type: array
                        token:
                          type: string
                        unsafeSkipCAVerification:
                          type: boolean
                      required:
                      - token
                      - unsafeSkipCAVerification
                      type: object
                    file:
                      properties:
                        kubeConfigPath:
                          type: string
                      required:
                      - kubeConfigPath
                      type: object
                    timeout:
                      type: object
                    tlsBootstrapToken:
                      type: string
                  required:
                  - tlsBootstrapToken
                  type: object
                kind:
                  type: string
                nodeRegistration:
                  properties:
                    criSocket:
                      type: string
                    kubeletExtraArgs:
                      type: object
                    name:
                      type: string
                    taints:
                      items:
                        type: object
                      type: array
                  type: object
              required:
              - nodeRegistration
              - caCertPath
              - discovery
              type: object
          type: object
        machineRef:
          type: string
        machineSpec:
          properties:
            datacenter:
              type: string
            datastore:
              type: string
            disks:
              items:
                properties:
                  diskLabel:
                    type: string
                  diskSizeGB:
                    format: int64
                    type: integer
                type: object
              type: array
            memoryMB:
              format: int64
              type: integer
            networks:
              items:
                properties:
                  ipConfig:
                    properties:
                      dns:
                        items:
                          type: string
                        type: array
                      gateway:
                        type: string
                      ip:
                        type: string
                      netmask:
                        type: string
                      networkType:
                        type: string
                    required:
                    - networkType
                    type: object
                  networkName:
                    type: string
                required:
                - networkName
                type: object
              type: array
            ntpServers:
              items:
                type: string
              type: array
            numCPUs:
              format: int32
              type: integer
            preloaded:
              type: boolean
            resourcePool:
              type: string
            template:
              type: string
            trustedCerts:
              items:
                type: string
              type: array
            vmFolder:
              type: string
            vsphereCloudInit:
              type: boolean
          required:
          - datacenter
          - datastore
          - networks
          - template
          - disks
          type: object
        metadata:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
