apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: vsphereclusterproviderconfigs.vsphereproviderconfig.sigs.k8s.io
spec:
  group: vsphereproviderconfig.sigs.k8s.io
  names:
    kind: VsphereClusterProviderConfig
    plural: vsphereclusterproviderconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        caKeyPair:
          properties:
            cert:
              format: byte
              type: string
            key:
              format: byte
              type: string
          required:
          - cert
          - key
          type: object
        clusterConfiguration:
          properties:
            apiServer:
              properties:
                certSANs:
                  items:
                    type: string
                  type: array
                extraArgs:
                  type: object
                extraVolumes:
                  items:
                    properties:
                      hostPath:
                        type: string
                      mountPath:
                        type: string
                      name:
                        type: string
                      pathType:
                        type: string
                      readOnly:
                        type: boolean
                    required:
                    - name
                    - hostPath
                    - mountPath
                    type: object
                  type: array
                timeoutForControlPlane:
                  type: object
              type: object
            apiVersion:
              type: string
            certificatesDir:
              type: string
            clusterName:
              type: string
            controlPlaneEndpoint:
              type: string
            controllerManager:
              properties:
                extraArgs:
                  type: object
                extraVolumes:
                  items:
                    properties:
                      hostPath:
                        type: string
                      mountPath:
                        type: string
                      name:
                        type: string
                      pathType:
                        type: string
                      readOnly:
                        type: boolean
                    required:
                    - name
                    - hostPath
                    - mountPath
                    type: object
                  type: array
              type: object
            dns:
              properties:
                imageRepository:
                  type: string
                imageTag:
                  type: string
                type:
                  type: string
              required:
              - type
              type: object
            etcd:
              properties:
                external:
                  properties:
                    caFile:
                      type: string
                    certFile:
                      type: string
                    endpoints:
                      items:
                        type: string
                      type: array
                    keyFile:
                      type: string
                  required:
                  - endpoints
                  - caFile
                  - certFile
                  - keyFile
                  type: object
                local:
                  properties:
                    dataDir:
                      type: string
                    extraArgs:
                      type: object
                    imageRepository:
                      type: string
                    imageTag:
                      type: string
                    peerCertSANs:
                      items:
                        type: string
                      type: array
                    serverCertSANs:
                      items:
                        type: string
                      type: array
                  required:
                  - dataDir
                  type: object
              type: object
            featureGates:
              type: object
            imageRepository:
              type: string
            kind:
              type: string
            kubernetesVersion:
              type: string
            networking:
              properties:
                dnsDomain:
                  type: string
                podSubnet:
                  type: string
                serviceSubnet:
                  type: string
              required:
              - serviceSubnet
              - podSubnet
              - dnsDomain
              type: object
            scheduler:
              properties:
                extraArgs:
                  type: object
                extraVolumes:
                  items:
                    properties:
                      hostPath:
                        type: string
                      mountPath:
                        type: string
                      name:
                        type: string
                      pathType:
                        type: string
                      readOnly:
                        type: boolean
                    required:
                    - name
                    - hostPath
                    - mountPath
                    type: object
                  type: array
              type: object
            useHyperKubeImage:
              type: boolean
          required:
          - etcd
          - networking
          - kubernetesVersion
          - controlPlaneEndpoint
          - dns
          - certificatesDir
          - imageRepository
          type: object
        etcdCAKeyPair:
          properties:
            cert:
              format: byte
              type: string
            key:
              format: byte
              type: string
          required:
          - cert
          - key
          type: object
        frontProxyCAKeyPair:
          properties:
            cert:
              format: byte
              type: string
            key:
              format: byte
              type: string
          required:
          - cert
          - key
          type: object
        kind:
          type: string
        metadata:
          type: object
        saKeyPair:
          properties:
            cert:
              format: byte
              type: string
            key:
              format: byte
              type: string
          required:
          - cert
          - key
          type: object
        sshAuthorizedKeys:
          items:
            type: string
          type: array
        vsphereCredentialSecret:
          type: string
        vspherePassword:
          type: string
        vsphereServer:
          type: string
        vsphereUser:
          type: string
      required:
      - vsphereServer
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
